### ISSUE TITLE
Hanging attributes

### ISSUE THREAD

**Issue by gArgyropoulos** [Georacer/Pure-MatSU#1]
Attributes of supervisor are undefined in global scope

simulation::75,78,81
vehicle-->supervisor.vehicle
gravity-->supervisor.gravity
propulsion-->supervisor.propulsion
aerodynamics-->supervisor.aerodynamics

**Comment by Georacer** [comment]
Closed by fb8df5f3864ca3bb24ad0a607867f2f06ed837a9
